/*
 * pkt_packetCommandsList.h
 *
 * Created: 7/29/2016 2:55:22 PM
 *  Author: Hriday Mehta
 */ 


#ifndef PKT_PACKETCOMMANDSLIST_H_
#define PKT_PACKETCOMMANDSLIST_H_

#define PACKET_TYPE_MASTER_CONTROL					0x01
#define PACKET_TYPE_IMU_SENSOR						0x03
#define PACKET_TYPE_PROTO_BUF						0x04
#define PACKET_TYPE_SUB_PROCESSOR					0x05
#define PACKET_TYPE_BLUETOOTH_MODULE				0x06

/*	Sensor module	*/
#define PACKET_COMMAND_ID_UPDATE					0x11
#define PACKET_COMMAND_ID_GET_FRAME					0x12
#define PACKET_COMMAND_ID_GET_FRAME_RESP			0x13
#define PACKET_COMMAND_ID_SETUP_MODE				0x14
#define PACKET_COMMAND_ID_BUTTON_PRESS				0x15
#define PACKET_COMMAND_ID_SET_IMU_ID				0x16
#define PACKET_COMMAND_ID_SET_IMU_ID_RESP			0x17
#define PACKET_COMMAND_ID_GET_STATUS				0x18
#define PACKET_COMMAND_ID_GET_STATUS_RESP			0x19
#define PACKET_COMMAND_ID_RESET_FAKE				0x20
#define PACKET_COMMAND_ID_UPDATE_FAKE				0x21
#define PACKET_COMMAND_ID_ENABLE_HPR				0x22
#define PACKET_COMMAND_ID_CHANGE_BAUD				0x23
#define PACKET_COMMAND_ID_SET_RATES					0x24
#define PACKET_COMMAND_ID_CHANGE_PADDING			0x25

/*	Power board / subProcessor messages	*/
#define PACKET_COMMAND_ID_SUBP_GET_STATUS			0x51
#define PACKET_COMMAND_ID_SUBP_GET_STATUS_RESP		0x52
#define PACKET_COMMAND_ID_SUBP_CONFIG				0x53
#define PACKET_COMMAND_ID_SUBP_STREAMING			0x54
#define PACKET_COMMAND_ID_SUBP_FULL_FRAME			0x55
#define PACKET_COMMAND_ID_SUBP_POWER_DOWN_REQ		0x56
#define PACKET_COMMAND_ID_SUBP_POWER_DOWN_RESP		0x57
#define PACKET_COMMAND_ID_SUBP_GET_DATE_TIME		0x58
#define PACKET_COMMAND_ID_SUBP_GET_DATE_TIME_RESP	0x59
#define PACKET_COMMAND_ID_SUBP_SET_DATE_TIME		0x5A
#define PACKET_COMMAND_ID_SUBP_SET_DATE_TIME_RESP	0x5B
#define PACKET_COMMAND_ID_SUBP_OUTPUT_DATA			0x5C
#define PACKET_COMMAND_ID_SUBP_AUTO_POWER_DOWN_REQ	0x5D
#define PACKET_COMMAND_ID_SUBP_FORCE_RESTART		0x5E

#define PACKET_COMMAND_ID_SUBP_ENTER_BOOTLOADER		0x5F
#define PACKET_COMMAND_ID_SUBP_BEGIN_FLASH_PROCESS	0x60
#define PACKET_COMMAND_ID_SUBP_BEGIN_FLASH_RESP	    0x61
#define PACKET_COMMAND_ID_SUBP_FLASH_DATA_BLOCK	    0x62
#define PACKET_COMMAND_ID_SUBP_FLASH_DATA_BLOCK_ACK 0x63

#endif /* PKT_PACKETCOMMANDSLIST_H_ */