/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: heddokoPacket.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "heddokoPacket.pb-c.h"
void   heddoko__imu_data_frame__init
                     (Heddoko__ImuDataFrame         *message)
{
  static Heddoko__ImuDataFrame init_value = HEDDOKO__IMU_DATA_FRAME__INIT;
  *message = init_value;
}
size_t heddoko__imu_data_frame__get_packed_size
                     (const Heddoko__ImuDataFrame *message)
{
  assert(message->base.descriptor == &heddoko__imu_data_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t heddoko__imu_data_frame__pack
                     (const Heddoko__ImuDataFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &heddoko__imu_data_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t heddoko__imu_data_frame__pack_to_buffer
                     (const Heddoko__ImuDataFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &heddoko__imu_data_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Heddoko__ImuDataFrame *
       heddoko__imu_data_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Heddoko__ImuDataFrame *)
     protobuf_c_message_unpack (&heddoko__imu_data_frame__descriptor,
                                allocator, len, data);
}
void   heddoko__imu_data_frame__free_unpacked
                     (Heddoko__ImuDataFrame *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &heddoko__imu_data_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   heddoko__full_data_frame__init
                     (Heddoko__FullDataFrame         *message)
{
  static Heddoko__FullDataFrame init_value = HEDDOKO__FULL_DATA_FRAME__INIT;
  *message = init_value;
}
size_t heddoko__full_data_frame__get_packed_size
                     (const Heddoko__FullDataFrame *message)
{
  assert(message->base.descriptor == &heddoko__full_data_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t heddoko__full_data_frame__pack
                     (const Heddoko__FullDataFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &heddoko__full_data_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t heddoko__full_data_frame__pack_to_buffer
                     (const Heddoko__FullDataFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &heddoko__full_data_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Heddoko__FullDataFrame *
       heddoko__full_data_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Heddoko__FullDataFrame *)
     protobuf_c_message_unpack (&heddoko__full_data_frame__descriptor,
                                allocator, len, data);
}
void   heddoko__full_data_frame__free_unpacked
                     (Heddoko__FullDataFrame *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &heddoko__full_data_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   heddoko__packet__init
                     (Heddoko__Packet         *message)
{
  static Heddoko__Packet init_value = HEDDOKO__PACKET__INIT;
  *message = init_value;
}
size_t heddoko__packet__get_packed_size
                     (const Heddoko__Packet *message)
{
  assert(message->base.descriptor == &heddoko__packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t heddoko__packet__pack
                     (const Heddoko__Packet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &heddoko__packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t heddoko__packet__pack_to_buffer
                     (const Heddoko__Packet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &heddoko__packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Heddoko__Packet *
       heddoko__packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Heddoko__Packet *)
     protobuf_c_message_unpack (&heddoko__packet__descriptor,
                                allocator, len, data);
}
void   heddoko__packet__free_unpacked
                     (Heddoko__Packet *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &heddoko__packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor heddoko__imu_data_frame__field_descriptors[15] =
{
  {
    "imuId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Heddoko__ImuDataFrame, imuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensorMask",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Heddoko__ImuDataFrame, has_sensormask),
    offsetof(Heddoko__ImuDataFrame, sensormask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quat_x_yaw",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Heddoko__ImuDataFrame, has_quat_x_yaw),
    offsetof(Heddoko__ImuDataFrame, quat_x_yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quat_y_pitch",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Heddoko__ImuDataFrame, has_quat_y_pitch),
    offsetof(Heddoko__ImuDataFrame, quat_y_pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quat_z_roll",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Heddoko__ImuDataFrame, has_quat_z_roll),
    offsetof(Heddoko__ImuDataFrame, quat_z_roll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quat_w",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Heddoko__ImuDataFrame, has_quat_w),
    offsetof(Heddoko__ImuDataFrame, quat_w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Mag_x",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Heddoko__ImuDataFrame, has_mag_x),
    offsetof(Heddoko__ImuDataFrame, mag_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Mag_y",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Heddoko__ImuDataFrame, has_mag_y),
    offsetof(Heddoko__ImuDataFrame, mag_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Mag_z",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Heddoko__ImuDataFrame, has_mag_z),
    offsetof(Heddoko__ImuDataFrame, mag_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Accel_x",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Heddoko__ImuDataFrame, has_accel_x),
    offsetof(Heddoko__ImuDataFrame, accel_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Accel_y",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Heddoko__ImuDataFrame, has_accel_y),
    offsetof(Heddoko__ImuDataFrame, accel_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Accel_z",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Heddoko__ImuDataFrame, has_accel_z),
    offsetof(Heddoko__ImuDataFrame, accel_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Rot_x",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Heddoko__ImuDataFrame, has_rot_x),
    offsetof(Heddoko__ImuDataFrame, rot_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Rot_y",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Heddoko__ImuDataFrame, has_rot_y),
    offsetof(Heddoko__ImuDataFrame, rot_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Rot_z",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Heddoko__ImuDataFrame, has_rot_z),
    offsetof(Heddoko__ImuDataFrame, rot_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned heddoko__imu_data_frame__field_indices_by_name[] = {
  9,   /* field[9] = Accel_x */
  10,   /* field[10] = Accel_y */
  11,   /* field[11] = Accel_z */
  6,   /* field[6] = Mag_x */
  7,   /* field[7] = Mag_y */
  8,   /* field[8] = Mag_z */
  12,   /* field[12] = Rot_x */
  13,   /* field[13] = Rot_y */
  14,   /* field[14] = Rot_z */
  0,   /* field[0] = imuId */
  5,   /* field[5] = quat_w */
  2,   /* field[2] = quat_x_yaw */
  3,   /* field[3] = quat_y_pitch */
  4,   /* field[4] = quat_z_roll */
  1,   /* field[1] = sensorMask */
};
static const ProtobufCIntRange heddoko__imu_data_frame__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 14, 12 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor heddoko__imu_data_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "heddoko.ImuDataFrame",
  "ImuDataFrame",
  "Heddoko__ImuDataFrame",
  "heddoko",
  sizeof(Heddoko__ImuDataFrame),
  15,
  heddoko__imu_data_frame__field_descriptors,
  heddoko__imu_data_frame__field_indices_by_name,
  2,  heddoko__imu_data_frame__number_ranges,
  (ProtobufCMessageInit) heddoko__imu_data_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor heddoko__full_data_frame__field_descriptors[2] =
{
  {
    "timeStamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Heddoko__FullDataFrame, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imuDataFrame",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Heddoko__FullDataFrame, n_imudataframe),
    offsetof(Heddoko__FullDataFrame, imudataframe),
    &heddoko__imu_data_frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned heddoko__full_data_frame__field_indices_by_name[] = {
  1,   /* field[1] = imuDataFrame */
  0,   /* field[0] = timeStamp */
};
static const ProtobufCIntRange heddoko__full_data_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor heddoko__full_data_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "heddoko.FullDataFrame",
  "FullDataFrame",
  "Heddoko__FullDataFrame",
  "heddoko",
  sizeof(Heddoko__FullDataFrame),
  2,
  heddoko__full_data_frame__field_descriptors,
  heddoko__full_data_frame__field_indices_by_name,
  1,  heddoko__full_data_frame__number_ranges,
  (ProtobufCMessageInit) heddoko__full_data_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue heddoko__packet__brain_pack_state__enum_values_by_number[4] =
{
  { "Idle", "HEDDOKO__PACKET__BRAIN_PACK_STATE__Idle", 0 },
  { "Recording", "HEDDOKO__PACKET__BRAIN_PACK_STATE__Recording", 1 },
  { "Reset", "HEDDOKO__PACKET__BRAIN_PACK_STATE__Reset", 2 },
  { "Error", "HEDDOKO__PACKET__BRAIN_PACK_STATE__Error", 4 },
};
static const ProtobufCIntRange heddoko__packet__brain_pack_state__value_ranges[] = {
{0, 0},{4, 3},{0, 4}
};
static const ProtobufCEnumValueIndex heddoko__packet__brain_pack_state__enum_values_by_name[4] =
{
  { "Error", 3 },
  { "Idle", 0 },
  { "Recording", 1 },
  { "Reset", 2 },
};
const ProtobufCEnumDescriptor heddoko__packet__brain_pack_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "heddoko.Packet.BrainPackState",
  "BrainPackState",
  "Heddoko__Packet__BrainPackState",
  "heddoko",
  4,
  heddoko__packet__brain_pack_state__enum_values_by_number,
  4,
  heddoko__packet__brain_pack_state__enum_values_by_name,
  2,
  heddoko__packet__brain_pack_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor heddoko__packet__field_descriptors[6] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Heddoko__Packet, type),
    &heddoko__packet_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Heddoko__Packet, has_state),
    offsetof(Heddoko__Packet, state),
    &heddoko__packet__brain_pack_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "brainPackVersion",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Heddoko__Packet, brainpackversion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "batteryCharge",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Heddoko__Packet, has_batterycharge),
    offsetof(Heddoko__Packet, batterycharge),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fullDataFrame",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Heddoko__Packet, fulldataframe),
    &heddoko__full_data_frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recordingName",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Heddoko__Packet, recordingname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned heddoko__packet__field_indices_by_name[] = {
  3,   /* field[3] = batteryCharge */
  2,   /* field[2] = brainPackVersion */
  4,   /* field[4] = fullDataFrame */
  5,   /* field[5] = recordingName */
  1,   /* field[1] = state */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange heddoko__packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor heddoko__packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "heddoko.Packet",
  "Packet",
  "Heddoko__Packet",
  "heddoko",
  sizeof(Heddoko__Packet),
  6,
  heddoko__packet__field_descriptors,
  heddoko__packet__field_indices_by_name,
  1,  heddoko__packet__number_ranges,
  (ProtobufCMessageInit) heddoko__packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue heddoko__packet_type__enum_values_by_number[9] =
{
  { "StateRequest", "HEDDOKO__PACKET_TYPE__StateRequest", 0 },
  { "StateResponse", "HEDDOKO__PACKET_TYPE__StateResponse", 1 },
  { "DataFrame", "HEDDOKO__PACKET_TYPE__DataFrame", 2 },
  { "BatteryChargeRequest", "HEDDOKO__PACKET_TYPE__BatteryChargeRequest", 3 },
  { "BatteryChargeResponse", "HEDDOKO__PACKET_TYPE__BatteryChargeResponse", 4 },
  { "BrainPackVersionRequest", "HEDDOKO__PACKET_TYPE__BrainPackVersionRequest", 5 },
  { "BrainPackVersionResponse", "HEDDOKO__PACKET_TYPE__BrainPackVersionResponse", 6 },
  { "SetRecordingName", "HEDDOKO__PACKET_TYPE__SetRecordingName", 7 },
  { "GetRecordingName", "HEDDOKO__PACKET_TYPE__GetRecordingName", 8 },
};
static const ProtobufCIntRange heddoko__packet_type__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex heddoko__packet_type__enum_values_by_name[9] =
{
  { "BatteryChargeRequest", 3 },
  { "BatteryChargeResponse", 4 },
  { "BrainPackVersionRequest", 5 },
  { "BrainPackVersionResponse", 6 },
  { "DataFrame", 2 },
  { "GetRecordingName", 8 },
  { "SetRecordingName", 7 },
  { "StateRequest", 0 },
  { "StateResponse", 1 },
};
const ProtobufCEnumDescriptor heddoko__packet_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "heddoko.PacketType",
  "PacketType",
  "Heddoko__PacketType",
  "heddoko",
  9,
  heddoko__packet_type__enum_values_by_number,
  9,
  heddoko__packet_type__enum_values_by_name,
  1,
  heddoko__packet_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
